#spring.application.name=pintrest
spring.application.name=pintrest





spring.datasource.url=jdbc:mysql://localhost:3306/capstone

spring.datasource.username=root

spring.datasource.password=nkpacmfb8m

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8765



// for dev purpose

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.autoconfigure.exclude = org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration





Auth.UserExists = "User already exists"

Auth.UserNotExists = "User Doesn't exists"

Auth.WrondPassword = "Wrong password. please enter correct password"



Service.BOARD_NOT_FOUND = "No board found for this user"

Service.PIN_NOT_FOUND = "No pin found"



Service.CANNOT_FOLLOW_SELF = "Following id should not be same as follower id"

Service.USER_NOT_FOUND="User does not exist"

Service.INVITATION_NOT_FOUND="No invitation found for this user"

Service.NOT_AUTHORIZED="Your are not authorized to perform this action"

